language:
  java
jdk:
  - oraclejdk8

before_script:
  - pip install --user codecov
script:
  - ./gradlew clean build

after_success:
  - ./gradlew jacocoTestReport
  - codecov

install: echo "Installing Camel Spring ..."

before_deploy:
  - zip build/libs/camel-1.0-SNAPSHOT.zip build/libs/camel-1.0-SNAPSHOT.jar
  - ls -al build/libs

deploy:
  - provider: s3
    access_key_id: AKIAJY6IDV4P7LQS2RVA
    secret_access_key: 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
    local_dir: build/libs
    skip_cleanup: true
    on: &2
      repo: TerrenceMiao/camel-spring
    bucket: camelspring-codedeploy
    region: ap-southeast-2
  - provider: codedeploy
    access_key_id: AKIAJY6IDV4P7LQS2RVA
    secret_access_key: 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
    bucket: camelspring-codedeploy
    key: camel-spring-1.0-SNAPSHOT.zip
    bundle_type: zip
    application: CamelSpringDemoApplication
    deployment_group: DevelopmentDemoFleet
    on: *2
    region: ap-southeast-2