language:
  java
jdk:
  - oraclejdk8

before_script:
  - pip install --user codecov
script:
  - ./gradlew clean build

after_success:
  - ./gradlew jacocoTestReport
  - codecov

install: echo "Installing Camel Spring ..."

before_deploy:
  - ls -al build/libs

deploy:
  - provider: s3
    access_key_id: AKIAJY6IDV4P7LQS2RVA
    secret_access_key: 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
    local_dir: build/libs
    skip_cleanup: true
    on: &2
      repo: TerrenceMiao/camel-spring
    bucket: camelspring-codedeploy
  - provider: codedeploy
    access_key_id: AKIAJY6IDV4P7LQS2RVA
    secret_access_key: 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
    bucket: camelspring-codedeploy
    key: camel-spring-1.0-SNAPSHOT.jar
    bundle_type: jar
    application: CamelSpringDemoApplication
    deployment_group: DevelopmentDemoFleet
    on: *2