language:
  java
jdk:
  - oraclejdk8

before_script:
  - pip install --user codecov
script:
  - ./gradlew clean build dist

after_success:
  - ./gradlew jacocoTestReport
  - codecov

install: echo "Installing Camel Spring ..."

before_deploy:
  - ls -al build/distributions

deploy:
  - provider: s3
    access_key_id: AKIAJY6IDV4P7LQS2RVA
    secret_access_key: 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
    local_dir: build/distributions
    skip_cleanup: true
    on: &2
      repo: TerrenceMiao/camel-spring
    bucket: camelspring-codedeploy
    region: ap-southeast-2
  - provider: codedeploy
    access_key_id: AKIAJY6IDV4P7LQS2RVA
    secret_access_key: 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
    bucket: camelspring-codedeploy
    key: camel-spring.zip
    bundle_type: zip
    application: org.paradise.MainSpringBootCamelRouter
    deployment_group: DevelopmentDemoFleet
    on: *2
    region: ap-southeast-2