version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/
hooks:
  BeforeInstall:
    - location: scripts/installOracleJDK8.bash
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/startApp.bash
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stopApp.bash
      timeout: 300
      runas: root